name: build

on:
  push:
    branches:
      - 'main'

jobs:
  main:
    env:
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      RELEASE_SIGNING_GRADLE: ${{ secrets.SIGNING_GRADLE }}
      RELEASE_KEYSTORE: ${{ secrets.KEYSTORE }}
      FIREBASE_TOKEN:  ${{ secrets.FIREBASE_TOKEN }}
      SS_URL:  ${{ secrets.SS_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting Release Module Files
        run: |
          mkdir -p app/src/release
          echo ${GOOGLE_SERVICES_JSON} | base64 -d > app/google-services.json
          echo ${RELEASE_SIGNING_GRADLE} | base64 -d > dependencies/signing.gradle
          echo ${RELEASE_KEYSTORE} | base64 -d > dependencies/release.keystore

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create Release Messages
        run: |
          curl -L "${SS_URL}" > release_message.json
          ./gradlew setReleaseMessage

      - name: Build
        run: ./gradlew clean assembleRelease

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: App Distribution Upload
        run: |
          git log -1 --format="%s [%ad] %an@%h" > dependencies/app-distribution-note.txt
          echo "" >> dependencies/app-distribution-note.txt
          git log --merges --first-parent --reverse --pretty=format:"* %s [%ad] %an@%h" >> dependencies/app-distribution-note.txt
          ./gradlew appDistributionUploadRelease
